CREATE TABLE IF NOT EXISTS genre
(
    id INTEGER PRIMARY KEY,
    name varchar(24) NOT NULL
);

CREATE TABLE IF NOT EXISTS rating_mpa
(
    id INTEGER PRIMARY KEY,
    name varchar(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(24) NOT NULL,
    description varchar(200),
    releaseDate date,
    duration INTEGER,
    rating_mpa_id INTEGER NOT NULL REFERENCES rating_mpa (id)
    CONSTRAINT duration_is_positive CHECK (duration > 0)
);

CREATE TABLE IF NOT EXISTS genre_film (
    film_id integer NOT NULL REFERENCES film (id),
    genre_id integer NOT NULL REFERENCES genre (id),
    UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(32) NOT NULL,
    login varchar(24) NOT NULL,
    name varchar(24),
    birthday date
);

CREATE TABLE IF NOT EXISTS film_like
(
    film_id INTEGER NOT NULL REFERENCES film (id),
    user_id INTEGER NOT NULL REFERENCES users (id),
    UNIQUE (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friend
(
    user_id INTEGER NOT NULL REFERENCES users (id),
    friend_id INTEGER NOT NULL REFERENCES users (id),
    UNIQUE(user_id, friend_id),
    CONSTRAINT many_users CHECK (user_id != friend_id)
);


